In [1]:
%matplotlib inline
import numpy as np

In [2]:
a = 1

In [3]:
print(a)


1


In [4]:
type(a)

int

In [6]:
b = 1.5
type(b)

float

In [7]:
list1 = [a, b, 1.5, 'string']

In [8]:
type(list1)

list

In [9]:
list2 = [0.5, 0.75, 1.0, 10.0]
print(list2)

[0.5, 0.75, 1.0, 10.0]


In [10]:
list3 = [1.1, 0.2, 0.4, 2e4]

In [11]:
print(list3)

[1.1, 0.2, 0.4, 20000.0]


In [12]:
list_sum = list2 + list3
print(list_sum)

[0.5, 0.75, 1.0, 10.0, 1.1, 0.2, 0.4, 20000.0]


In [13]:
vec2 = np.array(list2)
type(vec2)

numpy.ndarray

In [14]:
vec3 = np.array(list3)
print(vec3)

[1.1e+00 2.0e-01 4.0e-01 2.0e+04]


In [16]:
vec_sum = vec2 + vec3
print(vec2)
print('+')
print(vec3)
print('=')
print(vec_sum)

[ 0.5   0.75  1.   10.  ]
+
[1.1e+00 2.0e-01 4.0e-01 2.0e+04]
=
[1.600e+00 9.500e-01 1.400e+00 2.001e+04]


In [17]:
vec_dot = np.dot(vec2, vec3)
print(vec_dot)

200001.1


In [19]:
vec2[0]

0.5

In [28]:
print(vec2)

[ 0.5   0.75  1.   10.  ]


In [29]:
print( type(vec2[1]) )

<class 'numpy.float64'>


In [33]:
print( type( vec2[1:2]) )

<class 'numpy.ndarray'>


In [34]:
keep_inds = np.array([False, True, False, True])
print(keep_inds)

[False  True False  True]


In [35]:
print( vec2[keep_inds] )

[ 0.75 10.  ]


In [36]:
keep_inds2 = np.array([0, 1, 0, 1])
print( vec2[keep_inds2] )

[0.5  0.75 0.5  0.75]


In [39]:
print( type(keep_inds2[0]) )
print( type(keep_inds[0]) )

<class 'numpy.int64'>
<class 'numpy.bool_'>


In [40]:
print( vec3)

[1.1e+00 2.0e-01 4.0e-01 2.0e+04]


In [41]:
print( vec3 < 100.0 )

[ True  True  True False]


In [42]:
print( vec3[ (vec3< 100.0) ] )

[1.1 0.2 0.4]


# An now for something completely different....

### matrices...

In [43]:
list_of_list = [ [1.0, 0.2], [0.3, 1.2] ]
print(list_of_list)

[[1.0, 0.2], [0.3, 1.2]]


In [44]:
list_of_list[0]

[1.0, 0.2]

In [46]:
A = np.array(list_of_list)
print(A)

[[1.  0.2]
 [0.3 1.2]]


In [47]:
B = np.ones([2,2])
print(B)

[[1. 1.]
 [1. 1.]]


In [48]:
C_sum = A + B
print(C_sum)

[[2.  1.2]
 [1.3 2.2]]


In [49]:
C_mult = A*B
print(C_mult)

[[1.  0.2]
 [0.3 1.2]]


In [50]:
C_matmult = np.dot(A,B)
print(C_matmult)

[[1.2 1.2]
 [1.5 1.5]]


In [51]:
C_matmult2 = A@B
print(C_matmult2)

[[1.2 1.2]
 [1.5 1.5]]


In [53]:
A[0,1]

0.2

In [54]:
A[1,1]

1.2

In [55]:
A[0:2,0]

array([1. , 0.3])

In [56]:
A[:, 0]

array([1. , 0.3])

In [59]:
A[1,:] = np.array([0.4, 1.4])
print(A)

[[1.  0.2]
 [0.4 1.4]]


In [60]:
A[:,0] = np.array([0.2,0.3])

In [61]:
print(A)

[[0.2 0.2]
 [0.3 1.4]]


# Breakout Exercise
Goal: To create a matrix with three columns and 5 rows.  
- First column should be all ones.
- Second column should be x = [0.0,1.0,2.0,3.0,4.0]
- Third column should be x^2 = x*x

```
%matplotlib inline
import numpy as np
```

In [62]:
V = np.ones([5,3])
print(V)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [66]:

x = np.array([0.0, 1.0, 2.0, 3.0, 4.0])
x2 = x**2
print(x,x2)

[0. 1. 2. 3. 4.] [ 0.  1.  4.  9. 16.]


In [67]:
V[:,1] = x
V[:,2] = x2
print(V)

[[ 1.  0.  0.]
 [ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]]


In [69]:
y_obs = np.array([1.0, 3.1, 6.8, 13.2, 20.9])

$$
y = c_0 + c_1x + c_2x^2
$$

$$
x_{obs}  = [0,1,2,3,4]
$$
$$
y_{obs}  = [1,3.1,6.8,13.2,20.9]
$$

$$
\min_{c_0,c_1,c_2} \sum_{i=1}^5 (y_i - c_0 - c_1x_i - c_2x_i^2)^2
$$

$$
\min_{c_0,c_1,c_2} \left\| V\left[\begin{array}{c} c_0\\ c_1\\ c_2 \end{array}\right]- y_{obs}\right\|^2
$$

In [70]:
res = np.linalg.lstsq(V, y_obs)

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [71]:
coeffs = res[0]

(array([1.00571429, 1.01857143, 0.99285714]), array([0.09828571]), 3, array([19.62153847,  1.86319276,  0.72369934]))


In [ ]:
print(V@coeffs)
pr